services:
  - type: web
    name: mmommos-store
    env: python
    buildCommand: "apt-get update && apt-get install -y fonts-dejavu-core && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: admin123
      - key: DATABASE_URL
        value: postgresql://postgres:Admin%40333vlk@db.zwqtksiqkekcbwskwhsh.supabase.co:5432/postgres
      - key: SUPABASE_URL
        value: https://zwqtksiqkekcbwskwhsh.supabase.co
      - key: SUPABASE_KEY
        value: YOUR_SUPABASE_SERVICE_ROLE_KEY
      - key: SUPABASE_BUCKET
        value: uploads
